name: Check ESLint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: "npm run lint"
